# Generated by Django 3.2.6 on 2021-09-23 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bankapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer_Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=20)),
                ("account_number", models.CharField(max_length=11)),
                ("father_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.CharField(max_length=10)),
                ("dob", models.DateField()),
                ("balance", models.IntegerField()),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee_Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=20)),
                ("employee_email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=15)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="NewUser",
        ),
    ]
